# ????????? Logbook
logging.level.org.zalando.logbook: TRACE

# ????? ????????? ???????????
logging.level.ru.yandex.practicum.filmorate: DEBUG
logging.level.org.springframework.web: INFO
logging.level.org.hibernate: WARN

# ????????? Spring
spring.jackson.serialization.indent_output=true

# ????????? ??? ????????? (???????????)
server.error.include-message=always
server.error.include-binding-errors=always
